name = "tenwin-label"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages output directory - 构建输出目录
pages_build_output_dir = "./build/client"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "tenwin-label-db"
database_id = "9b039e2f-879a-47b0-b091-9a2747569934"

# KV Namespace
[[kv_namespaces]]
binding = "CACHE"
id = "9b039e2f-879a-47b0-b091-9a2747569934"

# 环境变量
[vars]
NODE_ENV = "production"
